Test/query log to stdout
manticoresoftware/docker pull request #60
Opened 2023-11-21 16:58 UTC by PavelShilin89

2023-11-23 11:00 UTC, djklim87 commented on clt_tests/tests/query_log_to_stdout.rep
> +You can use regex in the output sections.
For what reasons did we add this file to the repo? Maybe it should be ignored?

2023-11-23 14:50 UTC, merged

2023-11-23 15:52 UTC, sanikolaev requested changes

2023-11-23 15:52 UTC, sanikolaev commented on clt_tests/tests/query_log_to_stdout.rec
> +sleep 5;docker logs manticore | grep "accepting connections"
It's better not to use `sleep 5`, it may cause test instability.

2023-11-27 04:56 UTC, sanikolaev commented on clt_tests/tests/query_log_to_stdout.rec
> +sleep 5;docker logs manticore | grep "accepting connections"
I see this was ignored with no comment.